# Generated by Django 2.2.3 on 2019-08-04 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('ticket_type', models.CharField(choices=[('D', 'Defect'), ('F', 'Feature'), ('P', 'Patch')], default='D', max_length=1)),
                ('ticket_status', models.CharField(choices=[('N', 'New'), ('R', 'Read'), ('W', 'Waiting'), ('RP', 'Reopened'), ('RS', 'Resolved')], default='N', max_length=1)),
                ('updated', models.CharField(default=datetime.datetime(2019, 8, 4, 14, 22, 0, 481478), max_length=19)),
            ],
        ),
    ]
