# Generated by Django 2.2.3 on 2019-08-04 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=14)),
                ('lastname', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=18)),
                ('user_status', models.CharField(choices=[('A', 'Active'), ('D', 'Disabled'), ('P', 'Pending')], default='D', max_length=1)),
                ('created', models.DateField()),
                ('last_login', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated',
            field=models.CharField(default=datetime.datetime(2019, 8, 4, 14, 54, 22, 676914), max_length=19),
        ),
    ]
