# Generated by Django 2.2.3 on 2019-08-13 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190804_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='updated',
            field=models.CharField(default=datetime.datetime(2019, 8, 13, 14, 51, 5, 952373), max_length=19),
        ),
    ]
