# Generated by Django 2.2.3 on 2019-08-14 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190813_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.CharField(default='noname', max_length=18),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated',
            field=models.CharField(default=datetime.datetime(2019, 8, 14, 9, 17, 53, 281141), max_length=19),
        ),
    ]
