# Generated by Django 2.2.3 on 2019-08-24 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190814_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='updated',
            field=models.CharField(default=datetime.datetime(2019, 8, 24, 14, 0, 19, 761015), max_length=19),
        ),
    ]
