# Generated by Django 2.2 on 2020-04-29 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20200429_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='updated',
            field=models.CharField(default=datetime.datetime(2020, 4, 29, 14, 47, 34, 181120), max_length=19),
        ),
    ]
